### ISSUE TITLE
Offer to download the minified build

### ISSUE THREAD

**Issue by XhmikosR** [kangax/jscritic#12]
Might be worth adding this...

**Comment by kangax** [comment]
Ehh, not sure it's worth it. I wouldn't want to clutter it up with unnecessary functionality, especially considering that most of the scripts already have (un)official minified version and/or you can always plug it into uglify-js online interface, etc.

I'd rather focus on making jscritic detection more robust and things like that :) There's a lot to improve on.

**Comment by XhmikosR** [comment]
Yeah, I wasn't sure of this myself either :)
