### ISSUE TITLE
Useless console messages

### ISSUE THREAD

**Issue by XhmikosR** [kangax/jscritic#19]
I noticed them while trying to check #17. They are in jscritic.js.

**Comment by kangax** [comment]
Actually they are for when you run jscritic via node :)

**Comment by XhmikosR** [comment]
Well, sure but they offer nothing for the browser :/

**Comment by XhmikosR** [comment]
Let alone I was like "where the hell do those come from???" when I added a simple console.log to check the size.

**Comment by XhmikosR** [comment]
I still believe the messages should not pollute the browser's console. Isn't there a way to show them only in node?

**Comment by kangax** [comment]
> I still believe the messages should not pollute the browser's console.

Well, I don't imagine anyone using this script on a browser except on jscritic.com. And no one will use console on jscritic.com unless they're perhaps working on something in which case they'll know what messages are for :)

I just really don't see a need to get rid of them. If this was a "public" script to be used on a browser —  that would be a must.

**Comment by XhmikosR** [comment]
Well, even though one knows what they're doing, polluting the console isn't nice. I, for example, have to spend a lot more time trying to see my own logs.

Anyway, I guess I'll live with that.
