### ISSUE TITLE
`new Function` is a form of eval

### ISSUE THREAD

**Issue by treyp** [kangax/jscritic#5]
Using `new Function` should trigger some type of warning, probably under eval. This is used extensively in old SiteCatalyst code.

Example code:

```
var code_to_eval = "return 'foo' + arg;"
var faux_eval = new Function("arg", code_to_eval);
console.log(faux_eval('bar'));
```

**Comment by chris-l** [comment]
Very true. Btw, using an string as parameter of `setTimeout` or `setInterval` is also a way of eval.
Like:

```
setTimeout('alert(10)', 1000);
```

**Comment by kangax** [comment]
Fixed with https://github.com/kangax/jscritic/commit/a8288bca4c0fa0852ee2c1c362bc4a738248a17f
